MASTER PROMPT — "Keys to your freedom" Car Rental Website (PRODUCTION PROJECT, NOT A DEMO)
(Sent in 2 pastes. Read both before acting. Do not start work until Paste 2 is received.)

ROLE: Act as senior architect, PM, UI/UX, Django/Python, DB, security, QA, DevOps, frontend, PDF and WhatsApp-workflow engineer building a real production car-rental site for a small local business. Practical, maintainable, secure, responsive, mobile-first, lightweight, cost-conscious, easy for a non-technical owner, easy to extend. No enterprise over-engineering. Priorities: correct business logic, correct availability, manual owner control, simple booking flow, clear communication, policy acceptance, reliable PDF, customer WhatsApp confirmation workflow, security, maintainability, professional UI, deployment readiness.

WORKFLOW (MANDATORY): Work in PARTS: 1 Frontend Theme/Branding/UI; 2 DB/Cars/Availability; 3 Customer Booking + Rental Policy; 4 Admin + Confirmation + PDF + Customer WhatsApp; 5 Production Hardening/Deployment/Final QA. After EACH part: stop; run checks/tests; fix errors; explain what was implemented; list changed files; list tests actually run as PASSED / FAILED / NOT TESTED; known issues; manual testing steps; suggested Git commit; STOP. Never start the next part until the owner says "Proceed to Part N". Never claim something works untested.

FIRST ACTION: Inspect the whole existing project (Django project, apps, templates, static, CSS, JS, models, migrations, views, URLs, forms, admin, auth, DB/env config, car images/assets, booking, WhatsApp, customer fields, PDF; what works, what's incomplete, relevant tech debt). Don't blindly overwrite; reuse/extend working code; refactor only when necessary; explain major architectural changes first.

SOURCES OF TRUTH: A) This prompt: business logic, booking, availability, policy, confirmation, PDF, WhatsApp, admin, security, DB, stack, architecture. B) The supplied screenshot = PRIMARY visual reference (theme, colors, logo, cards, buttons, typography, nav, spacing, mobile layout, car cards, pricing, status pills, WhatsApp CTA). Adapt its design language; don't copy placeholder data. If it conflicts with business logic, BUSINESS LOGIC WINS; keep working functionality while matching the screenshot as closely as reasonable.

BUSINESS NAME: "Keys to your freedom" is official, NOT a placeholder. Never ask to change it or invent another (no ABC Rentals, Demo Rental, Company Name, etc.). Use everywhere: navbar, logo, all pages, footer, policy, PDF, admin, WhatsApp messages, metadata, titles. Store in BusinessSettings.business_name (default "Keys to your freedom"); use that value in templates instead of hardcoding; fallback is the same name.
LOGO: reuse an existing asset; if missing, build the UI so the real logo can be inserted later; no new brand identity; readable on desktop/tablet/mobile, undistorted, unstretched, proper object-fit/position.

DESIGN: The old lavender/grey theme is obsolete; the screenshot is primary. Dark, premium, modern, automotive, compact, high contrast, mobile-first, clean, professional. Very dark navy/near-black background; slightly lighter dark cards; subtle borders; cyan/light-blue primary actions; orange/yellow for selected/highlight/warning; green for WhatsApp/success; red for danger; white/off-white text; muted grey secondary text. No rainbow UI. Use centralized CSS variables (--color-bg, surface, surface-elevated, border, text-primary/secondary/muted, primary, primary-hover, accent, success, warning, danger) matched to the screenshot; no scattered raw colors.
Typography: strong readable headings, reliable clean sans-serif, compact labels, clear pricing, readable mobile text, nothing tiny. Keep prominent: car name, price, availability, booking status, primary action, policy acceptance, booking reference, customer WhatsApp number.
Cards: rounded, dark, subtle borders, small shadows, clear hierarchy, compact, strong images. Car card: image, optional badge, brand/model, price, rental-period label, key specs, included km, WhatsApp inquiry button, Request/Reserve button; uncluttered, obvious primary action.
Mobile: genuinely usable, not a shrunk desktop (mobile/tablet/laptop/desktop): header, logo, nav, search, filters, cards, buttons, booking form, policy, admin, PDF/WhatsApp/call actions, booking summary. Fixed mobile bottom nav like the screenshot (Home, Cars, Bookings/customer area, Support/Contact; only pages that really exist, no fake tabs), active tab highlighted, enough bottom padding, hidden on large desktop.

BUSINESS MODEL: Owner-controlled lead-generation + booking-request system, NOT instant booking. Flow: browse cars → dates → pickup location → car → details → read and accept policy → submit → PENDING → customer sees request received and contacts owner → owner reviews, checks live availability, confirms/rejects → if confirmed: PDF, summary, customer WhatsApp workflow → offline payment → pickup → return → owner inspection → deposit/damage handling → COMPLETED.

BOOKING RULES: Submitting NEVER confirms. status = PENDING, never auto-CONFIRMED. Customer must see "Your booking is NOT confirmed yet." (or identical meaning). Never say confirmed/reserved/payment successful/booking successful unless it actually happened. Only authenticated authorized owner/admin can confirm; customers never confirm. "Customer confirmation" in the WhatsApp workflow means the OWNER confirmed the customer's booking.
Statuses: PENDING (not confirmed, doesn't block), CONFIRMED (owner confirmed, blocks availability), REJECTED (no block), CANCELLED (previously confirmed, no longer blocks), COMPLETED (rental done, vehicle returned, history preserved).

BOOKING FORM: Collect only what's required. Customer: full name, mobile, WhatsApp number, email, optional address only if genuinely required. Booking: selected car, pickup location, pickup date/time, return date/time, preferred contact method, message. No government ID uploads, no public document upload, no unnecessary sensitive data.
WhatsApp number is collected BEFORE submission; label "WhatsApp Number"; helper: "Your booking confirmation and summary may be sent to this WhatsApp number after the owner confirms your booking." Offer "[ ] Same as mobile number"; never assume they're the same unless the customer selects it.
SERVER-SIDE VALIDATION (never JS only): required fields, phone, WhatsApp, email if given, car exists/active, pickup location active, valid pickup/return datetimes, return after pickup, reasonable period, valid customer details, policy acceptance/version/snapshot, CSRF. On failure: create no booking, show clear errors, preserve valid input. Normalize WhatsApp to international format; show the normalized value; never silently change it.
REFERENCE: server-generated, unique, human-friendly (e.g. KTF-2026-0001), easy to read/print/send on WhatsApp/PDF; never client-provided.

AVAILABILITY (CRITICAL): Publicly available only if car ACTIVE, no overlapping manual block, no overlapping CONFIRMED booking. PENDING never blocks. Consistent everywhere.
Car status: ACTIVE, INACTIVE, MAINTENANCE (latter two not publicly bookable).
AvailabilityBlock: car, start, end, reason (OFFLINE_BOOKING, RESERVED, MAINTENANCE, PERSONAL_USE, UNAVAILABLE, CLEANING, OTHER), notes, created_by, created/updated at. Independent of bookings; affects public availability.
One central reusable service, e.g. is_car_available(car, pickup_datetime, return_datetime); never duplicate logic in views. Checks car status, manual blocks, confirmed bookings. Overlap: existing_start < requested_end AND existing_end > requested_start.
On Confirm, ALWAYS do a fresh server-side revalidation (car status, blocks, confirmed overlaps, booking still PENDING); don't trust availability from submission time. Conflict → don't confirm, show clear error, keep PENDING. Available → confirm, set confirmed_at and confirmed_by; prevent overlapping confirmed bookings.

WHATSAPP: Use deep links (https://wa.me/?text=<encoded_message>). Never claim a normal deep link auto-sends; the user must press send. Architecture supports A) manual deep-link workflow and B) automatic delivery via an official WhatsApp Business API/provider only if explicitly configured (don't add a provider to V1 without owner approval).
After submission show WHATSAPP OWNER with prefilled message: business name, customer name, booking reference, car, pickup date/time, return date/time, location, "Please help me confirm availability." Never "Booking confirmed" (still PENDING). Also show CALL OWNER (tel:) on the submitted page, contact page, relevant booking areas.

RENTAL RESPONSIBILITY POLICY (mandatory, shown BEFORE submission): short, clear, mobile-friendly, compact card integrated in the booking flow ("VEHICLE CARE & DAMAGE POLICY", optional "Read full policy"), not a wall of legal text. Checkbox UNCHECKED by default: "I have read and agree to the Vehicle Care & Damage Policy." Submit disabled/rejected until explicitly checked; scrolling or opening the policy is NOT acceptance.
Content must convey: renter is responsible for the vehicle during the rental and must take reasonable care; new damage, accident-related damage or loss caused during the rental may result in charges to the renter per the agreed rental terms and applicable law; vehicle returned in agreed condition; vehicle checked at/before pickup and existing damage identified/documented where possible; renter must immediately inform Keys to your freedom of any accident, damage, breakdown or incident; new damage found after the rental may be assessed by the owner; damage charges may be recorded against the booking. No absolute claims (e.g. "Owner has absolutely no responsibility under any circumstances"); use "subject to the agreed rental terms and applicable law." End: "By accepting this policy, the renter acknowledges these responsibilities." Wording admin-configurable where practical.
AUDITABLE ACCEPTANCE: BookingPolicyAcceptance (booking, accepted, policy version, policy title, exact policy text snapshot, accepted_at, created_at; IP/user-agent only if justified). Never just a boolean. If policy changes (v1.0 → v1.1), old bookings keep v1.0 and its exact text. Acceptance does NOT mean confirmed, reserved, paid or availability guaranteed; booking stays PENDING. Legacy bookings without acceptance show "POLICY ACCEPTANCE NOT AVAILABLE FOR THIS BOOKING"; never fabricate acceptance. No normal booking may exist without acceptance.
SUBMISSION FLOW (transactional, no half-complete bookings): validate booking → validate policy acceptance → fetch current policy → create customer → create booking PENDING → store policy version/snapshot/timestamp → generate reference → show submitted page.
SUBMITTED PAGE: "BOOKING REQUEST RECEIVED"; prominently "YOUR BOOKING IS NOT CONFIRMED YET."; show reference, customer name, car, pickup/return date-time, pickup location, customer WhatsApp where appropriate, status PENDING; buttons WHATSAPP OWNER and CALL OWNER; text: "Your request has been received. Please contact the owner on WhatsApp or by phone to discuss and confirm availability." Don't imply the owner will contact the customer. No confirmation message at this stage.
(Continued in Paste 2)
MASTER PROMPT — "Keys to your freedom" (continued, Paste 2 of 2)

OWNER CONFIRMATION: Two buttons: CONFIRM BOOKING (no WhatsApp required) and CONFIRM & SEND WHATSAPP. Owner is not forced to use WhatsApp. Neither may bypass availability revalidation or policy checks; confirmation and WhatsApp delivery are separate operations. Before confirming verify: availability, car active, no manual block, no confirmed overlap, booking still PENDING, customer details, customer WhatsApp present/valid (warn admin clearly if missing), policy acceptance exists. Then status=CONFIRMED, confirmed_at, confirmed_by; save; generate PDF; store it; associate with booking; make it accessible to authorized admin; prepare customer summary and WhatsApp confirmation.
Customer WhatsApp number MUST come from Booking → Customer → WhatsApp number. Never use the owner's number, pickup-location number, a random/stored/guessed number, or a previous customer's number. If missing, don't use another number unless the customer explicitly chose "same as mobile". Trigger only after the booking is CONFIRMED and the DB transaction completed; never while PENDING; never customer-triggered. Store a booking-level WhatsApp snapshot only if needed for historical accuracy.
WITH official provider configured: send summary to customer's WhatsApp, send PDF if provider supports documents, record provider response and delivery status, handle failures. Text-only provider: send summary, deliver PDF another way, don't claim the PDF was sent via WhatsApp.
WITHOUT provider: booking confirms normally; PDF auto-generated and stored; admin sees customer number, Download PDF, Open WhatsApp (deep link to the CUSTOMER's number with prefilled confirmation), Share PDF where browser/device supports it; owner sends/attaches manually; UI says "Manual WhatsApp Send Required". Never display "Automatically sent" or mark SENT unless the provider confirmed. Never claim PDF/summary sent unless actually sent. WhatsApp failure never reverts CONFIRMED; PDF stays stored; admin sees failure/pending and can retry or send manually. Don't block the confirmation transaction on WhatsApp: confirm → commit → generate PDF → run communication safely → record result.
SUMMARY MESSAGE (generated dynamically, only existing fields, no invented data): business name, greeting/customer name, reference, status CONFIRMED, car brand/model, registration if appropriate, pickup date/time/location, return date/time, rental duration, price/day, total, amount paid, balance (only if recorded), note that the confirmation document was generated, keep the reference, business phone/WhatsApp, pickup instructions if configured. E.g. "Hi [Name], Your booking with Keys to your freedom has been confirmed. Booking Reference: KTF-2026-0001 ... Thank you, Keys to your freedom [Business Phone]".
BookingCommunication (kept with booking for audit): booking, recipient type, recipient phone, channel WHATSAPP, message type (BOOKING_CONFIRMATION, BOOKING_CONFIRMATION_WITH_DOCUMENT, BOOKING_REQUEST, OTHER), message snapshot, document, status (NOT_CONFIGURED, READY_TO_SEND, QUEUED, SENT, DELIVERED, FAILED, MANUAL_SEND_REQUIRED), provider, provider message ID, sent/delivered/failed at, failure reason, created/updated. No unnecessary sensitive data. Phone numbers stored securely, never public, international format for links/provider.

MODELS: Car: brand, model, display name, class (Hatchback, Sedan, SUV, MUV, 7-Seater, Luxury, Other), registration, price/day, seats, fuel (Petrol, Diesel, CNG, EV, Hybrid, Other), transmission (Manual, Automatic, AMT, Other), gearbox label, AC, included km, description, rental rules, extra charges, status, archived, timestamps. CarImage: main/gallery, order, active, alt text; Cloudinary in production (not local Render storage). Customer: name, phone, WhatsApp, email, optional address, notes, timestamps; never public. Booking: reference, car, customer, pickup location, pickup/return datetime, message, contact preference, status, confirmed_at/by, timestamps; keep history; no duplicate policy fields. BusinessSettings (singleton): name, logo, phone, WhatsApp, email, currency, business hours, rental rules, rental policy, policy version, default security deposit, notes, provider status, timestamps; provider secrets ONLY in env vars. PickupLocation: name, address, city, state, postal code, Google Maps link (no Maps API), phone/WhatsApp override, pickup instructions, active, timestamps. PaymentRecord (offline records only; NO Razorpay/Stripe/PayPal/card/UPI gateway, no automated payment confirmation): booking, total, amount paid, remaining, status (UNPAID, PARTIAL, PAID, REFUNDED), method (Cash, UPI, Bank Transfer, Other), date, notes. Security deposit: amount, status, arrangement, date received/returned, amount returned, notes; no government IDs. DamageIncident: booking, car, type (ACCIDENT, DAMAGE, SCRATCH, DENT, GLASS, TYRE, INTERIOR, MECHANICAL, OTHER), date, description, existing/new, estimated/final cost, customer responsibility amount, notes, status; records owner's assessment, never auto-charges. Use DB constraints, unique reference, valid date ranges; archive rather than delete history.

ADMIN: Django auth; only authorized admins may confirm/reject/cancel/complete, manage blocks/cars/prices/policy/settings, record payment/deposit/damage, view customer info, PDFs, WhatsApp details, retry delivery. Dashboard (no needless analytics): pending requests, confirmed bookings, today's pickups, upcoming returns, available cars, manual blocks, payment/deposit pending, recent incidents, WhatsApp confirmations needing attention; manage cars, images, locations, blocks, bookings, customers, payments, deposits, damage, settings, policy, PDFs, WhatsApp status.
Booking list: search; filters (status, car, date, pickup location); sort newest/upcoming; show reference, customer, car, pickup, return, status, created date, payment status, policy status, PDF availability, customer WhatsApp availability, WhatsApp delivery status.
Booking detail: CUSTOMER (name, phone, WhatsApp, email); BOOKING (reference, car, pickup, return, location, message, contact preference, status); AVAILABILITY (AVAILABLE or CONFLICT — cannot confirm, with reasons: confirmed booking, manual block, inactive, maintenance); POLICY (accepted, version, timestamp, exact snapshot); DOCUMENTS (PDF download, generate/regenerate, delivery status); WHATSAPP (customer number, message preview, delivery/provider status, retry, open WhatsApp, manual send/share instructions); ACTIONS (Confirm, Confirm & Send WhatsApp, Reject, Cancel, Mark completed, Record payment/deposit/damage, Call customer, Download/Share PDF).
Calendar (month/week/timeline) distinguishing CONFIRMED BOOKING, PENDING REQUEST (doesn't block), MANUAL BLOCK; admin can create/remove blocks. Admin works on mobile: cards, stacked tables, horizontal scroll only where necessary, careful sticky actions, accessible Confirm/PDF/WhatsApp actions, readable policy and status.

PUBLIC PAGES/UI: Home, Cars, Car Details, Booking Request, Booking Submitted, About, Contact, Rental Rules, Privacy, optional Rental Policy. Home (uncluttered, strong automotive imagery): header, logo, hero, search, featured cars, benefits, rental process, pickup locations, policy assurance, WhatsApp CTA, Call CTA, footer, bottom nav. Listing: image, name, price/day, class, seats, fuel, transmission, AC, included km, availability, WhatsApp inquiry, Request button; filters: date, pickup location, class, gearbox, price. Detail: gallery, main image, specs, description, rules, extra charges, pickup options, selected dates, booking and WhatsApp CTA; say "Request Booking", NOT "Instant Booking". Booking form sections: CUSTOMER DETAILS, BOOKING DETAILS, VEHICLE, RENTAL POLICY, FINAL REVIEW; dark cards, clear labels, large touch controls; WhatsApp field clearly visible with "[ ] Same as mobile number" and helper "This number will be used for your booking confirmation communication if WhatsApp delivery is enabled." Policy card integrated in flow, then SUBMIT BOOKING REQUEST.
Buttons: primary cyan (Request Booking, Reserve Car, Confirm Booking, Continue, Submit Request); green WhatsApp (WhatsApp Owner, WhatsApp Inquiry, Confirm & Send WhatsApp, Send Booking Summary); orange warning (Pending, Attention required, Manual WhatsApp Send Required); red danger (Cancel, Reject, Delete); secondary dark/outlined. Badges always with text, not color only: PENDING orange, CONFIRMED green, REJECTED red, CANCELLED muted/red, COMPLETED blue/green; WhatsApp: SENT blue/green, DELIVERED green, FAILED red, MANUAL SEND REQUIRED orange, NOT CONFIGURED muted.
Templates: base.html (public), admin_base.html (admin); reusable components: navbar, bottom nav, footer, buttons, cards, car cards, forms, alerts, badges, modals, booking summary, policy card, admin nav, PDF card, WhatsApp CTA, confirmation card, delivery status. UI states: loading, empty, success, error, validation error, disabled, conflict, unavailable, pending/confirmed/rejected/cancelled/completed; WhatsApp: not configured, ready, sending, sent, delivered, failed, manual send required; no empty placeholder blocks. Accessibility: semantic HTML, labels, keyboard, focus states, alt text, contrast, clear errors, accessible policy checkbox and WhatsApp input, clearly labeled WhatsApp/Call buttons. SEO: titles, meta descriptions, heading hierarchy, clean URLs, Open Graph. Performance: select_related/prefetch_related, pagination, optimized images, minimal JS. Errors: 404, 500, form errors, conflicts, unauthorized, PDF/document/WhatsApp errors; never expose stack traces, secrets, passwords, DB/WhatsApp credentials.

STACK (FIXED): Django; HTML, CSS, vanilla JS, Django templates; SQLite dev; PostgreSQL (Neon) prod; Cloudinary media; Render hosting; Cloudflare DNS + custom domain; Git + GitHub; reliable Python/Django PDF approach; official WhatsApp API only if configured. NO React, Next.js, Node backend, microservices, Kubernetes, GraphQL, Redis, Celery or Docker unless genuinely required and approved. Use .env (never commit), provide .env.example: SECRET_KEY, DEBUG, DATABASE_URL, CLOUDINARY_CLOUD_NAME/API_KEY/API_SECRET; later provider vars (WHATSAPP_PROVIDER, WHATSAPP_API_URL, WHATSAPP_API_TOKEN, WHATSAPP_PHONE_NUMBER_ID). Never expose secrets in HTML/JS/API responses/logs. Security: CSRF, auth, secure passwords/sessions/cookies, HTTPS, permission checks, server validation, ORM, XSS-safe templates; customers never access others' bookings; customer WhatsApp numbers never public.

PARTS:
PART 1 Frontend: CSS variables, dark theme, typography, buttons, cards, badges, forms, navbar, logo, bottom nav, footer, Home, Cars, Car details, booking form UI, submitted UI, policy card UI, WhatsApp field UI, Contact, About, Rules, Privacy, admin shell, responsive layouts, confirmation/summary UI, delivery-status placeholders. No full DB/booking logic unless present; don't pretend policy acceptance or automatic delivery works yet. Tests: server runs, pages load, responsive, navigation, no major console errors, theme consistency, screenshot hierarchy, mobile/desktop, WhatsApp field works as form component, confirmation UI makes no automatic-delivery claim. Then summary, files, tests, issues, manual testing, Git commit; STOP; wait "Proceed to Part 2".
PART 2 DB/Cars/Availability: BusinessSettings, PickupLocation, Car, CarImage, AvailabilityBlock, Customer foundation, availability service, admin CRUD (cars, images, locations, blocks), calendar, public availability filtering, WhatsApp field foundation. Tests: ACTIVE car appears; block hides it in period and it reappears outside; INACTIVE/MAINTENANCE hidden; date/class/transmission filters correct; WhatsApp data stored securely and not public; PENDING never blocks. STOP; wait "Proceed to Part 3".
PART 3 Booking + Policy: Customer, Booking, reference, booking form, server validation, PENDING, WhatsApp number stored with customer/booking, policy model/versioning/snapshot/timestamp, mandatory checkbox, submission, submitted page, WhatsApp owner and call links, admin list/detail, live availability, confirmation-time revalidation, policy in admin. Tests: policy unchecked blocks submission; checked works; booking created, reference generated, PENDING; WhatsApp stored correctly; version/snapshot/timestamp stored; customer sees NOT CONFIRMED; owner WhatsApp link and call work; admin sees policy, request, customer WhatsApp; revalidation works. STOP; wait "Proceed to Part 4".
PART 4 Admin + Confirmation + PDF + WhatsApp: full dashboard, payments, deposits, damage, policy management, Confirm Booking, Confirm & Send WhatsApp, confirmation timestamp/user, PDF generate/store/download with exact policy snapshot, document management, delivery workflow, settings, locations, calendar refinements, customer WhatsApp confirmation, communication records, delivery status, manual fallback (process as defined above; customer and owner numbers never confused). Tests: confirm available booking; PDF generated, stored, downloadable, correct booking and exact accepted policy; customer number retrieved correctly; message has correct customer, reference, dates, pickup location; no confirmation while PENDING; automatic delivery works if provider configured and status recorded; manual fallback works otherwise; no false automatic-delivery claims; conflict prevents confirmation; WhatsApp failure doesn't cancel confirmed booking; retry/manual send works. STOP; wait "Proceed to Part 5".
PART 5 Hardening/Deployment/QA: full QA. Customer: home, search, cars, details, booking, WhatsApp number, policy, acceptance, pending, WhatsApp owner, call, mobile, confirmed-booking communication. Admin: login, dashboard, cars, images, availability, bookings, policy, confirm/reject/cancel/complete, payments, deposits, damage, PDF, settings, customer WhatsApp, delivery status, manual fallback. Logic: PENDING doesn't block; CONFIRMED, manual blocks, inactive, maintenance block; confirmation revalidates; no overlapping confirmed bookings; policy required, doesn't confirm, snapshot preserved and in PDF; PDF after confirmation; customer number from booking/customer data; confirmation only after owner confirmation; no false WhatsApp claims; failure doesn't undo confirmation. Security: CSRF, auth, authorization, secrets, HTTPS, secure cookies, env vars, no public customer data/WhatsApp numbers/credentials. Production: Neon, Cloudinary, Render, Cloudflare, static, media, PDF storage, migrations, logging, error handling, provider config if enabled, delivery failure handling.

TESTING: Never claim tests passed unless run. Automated: Django checks; model, availability, booking, policy, permission, form-validation, PDF, confirmation, conflict, WhatsApp validation/message/delivery-state, communication-authorization tests. Manual: customer flow, WhatsApp entry, policy, booking, WhatsApp owner, call, admin confirmation, PDF, customer confirmation, manual fallback, availability, mobile/desktop. Report after every part as: TEST RESULTS / PASSED / FAILED / NOT TESTED / KNOWN ISSUES.
GIT: commits "part 1: new theme and frontend ui", "part 2: database cars and availability", "part 3: booking and rental policy", "part 4: admin confirmation pdf and customer whatsapp", "part 5: production hardening and deployment". Before commit: git status, git diff, check secrets, confirm .env ignored, check migrations, run relevant tests. Never commit .env, API keys, passwords, Cloudinary/DB/Django secrets, private tokens, WhatsApp credentials.

NEVER: auto-confirm bookings; treat PENDING as CONFIRMED; let customers confirm; ignore availability or manual blocks; allow overlapping confirmed bookings; depend on owner contacting customer; add a payment gateway in V1; collect unnecessary sensitive data; expose customer info; hardcode secrets; fake WhatsApp sending; claim PDF or summary sent when not; lose or replace accepted policy text for historical bookings; allow submission without policy acceptance; treat acceptance as confirmation; fake payment/customer/car info; replace "Keys to your freedom" or treat it as placeholder; skip testing; continue to next PART without permission; rewrite working code unnecessarily; send customer confirmation to owner's number; guess customer's number; trigger confirmation while PENDING; mark delivery successful without real provider confirmation; expose WhatsApp credentials; let WhatsApp failure revert CONFIRMED to PENDING.

DEFINITION OF DONE:
CUSTOMER can browse/filter cars, select dates and pickup location, see genuine availability, view details, enter mobile and WhatsApp numbers, read and accept policy, submit, get a unique reference, see PENDING and clearly NOT CONFIRMED, WhatsApp/call owner; after owner confirmation receive the summary via the configured WhatsApp workflow and the confirmation document where supported.
OWNER can log in; manage cars, images, availability, locations; view requests and customers; see live availability; confirm/reject/cancel/complete; record payment/deposit/damage; edit policy; see policy acceptance; generate/download/share PDF; see customer WhatsApp; send confirmation; see/retry delivery; use manual fallback; manage settings.
POLICY: visible before submission, understandable, short, explicit acceptance, stores version + exact text + timestamp, appears in admin and confirmed PDF, historically accurate, never confirms the booking.
PDF (after owner confirmation): associated with booking; correct reference, customer, vehicle, dates, pickup location; policy version, exact snapshot, acceptance and confirmation timestamps; branding; downloadable; delivery workflow available.
WHATSAPP CONFIRMATION: only after owner confirmation; number from the booking; correct reference, name, vehicle, pickup/return, business info; financials only if recorded; no fake info. Provider configured: summary sent to customer number, PDF where supported, response/status recorded, failures recorded, retry/fallback available. No provider: PDF still auto-generated, number visible to authorized admin, Open WhatsApp with prefilled message, PDF download/share, manual send, UI says "Manual WhatsApp Send Required", no automatic-delivery claim.
AVAILABILITY: ACTIVE can be available; INACTIVE, MAINTENANCE, manual blocks, CONFIRMED bookings unavailable; PENDING doesn't block; confirmation re-checks; overlap prevention works.
PRODUCTION ready only when PostgreSQL, Cloudinary, Render, Cloudflare, HTTPS, static files, media, PDF storage, env vars, migrations, authentication, authorization and security settings work; major tests pass; mobile/desktop work; no secrets committed; provider works if configured (or manual fallback works); customer WhatsApp data protected; delivery status accurate.

START NOW: FIRST inspect the existing project; don't immediately rewrite code. Then begin ONLY PART 1 using the screenshot as the visual reference. Don't implement all parts at once, skip parts, or continue automatically. At the end of PART 1: summarize, list changed files, tests (PASSED/FAILED/NOT TESTED), known issues, manual testing instructions, suggested Git commit; STOP; wait for "Proceed to Part 2".
When something is undefined, choose the simplest production-safe implementation consistent with this document and explain the decision. This is a real business: no fake functionality, success states, payments, availability, PDF delivery or WhatsApp delivery; don't silently make business decisions. Always preserve "Keys to your freedom" and the flow: request → PENDING → owner verifies → owner confirms → PDF generated → customer summary prepared → customer WhatsApp workflow → offline payment. Never falsely tell a customer a submitted request is confirmed. Policy must be accepted before submission, preserved, and included in the confirmation PDF, which is generated only after owner confirmation. The customer's WhatsApp number comes from the booking/customer form; after owner confirmation the summary goes to that number via an official provider if configured, otherwise via a clear manual workflow that NEVER pretends the message or PDF was sent automatically. Owner and customer WhatsApp numbers must never be confused. WhatsApp failure must NOT undo a valid confirmation. Do not proceed to the next PART without explicit permission.
END OF MASTER PROMPT
