# Generated by Django 6.1.1 on 2026-10-01 18:16

import datetime
import django.db.models.deletion
import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=60)),
                ("model", models.CharField(max_length=80)),
                (
                    "vehicle_class",
                    models.CharField(
                        choices=[
                            ("SUV", "SUV / Compact SUV"),
                            ("Hatchback", "Hatchback"),
                            ("Sedan", "Sedan"),
                            ("MUV", "MUV / 7-Seater"),
                            ("Luxury", "Luxury"),
                        ],
                        default="SUV",
                        max_length=30,
                    ),
                ),
                (
                    "price_per_day",
                    models.PositiveIntegerField(
                        help_text="Daily rental rate in ₹ (INR)"
                    ),
                ),
                (
                    "security_deposit",
                    models.PositiveIntegerField(
                        default=3000, help_text="Refundable deposit in ₹ (INR)"
                    ),
                ),
                ("seats", models.PositiveSmallIntegerField(default=5)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("EV", "Electric Vehicle (EV)"),
                            ("CNG", "CNG"),
                        ],
                        default="Petrol",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Manual", "Manual"), ("Automatic", "Automatic")],
                        default="Manual",
                        max_length=20,
                    ),
                ),
                ("ac_status", models.CharField(default="Cold A/C", max_length=40)),
                (
                    "included_km",
                    models.PositiveIntegerField(
                        default=250, help_text="Free KM per day"
                    ),
                ),
                (
                    "extra_km_rate",
                    models.PositiveSmallIntegerField(
                        default=12, help_text="Extra charge per KM beyond limit"
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Popular, Economic, 7-Seater",
                        max_length=40,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        default="", help_text="Direct image URL", max_length=500
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["-is_featured", "price_per_day"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location / Terminal Name", max_length=150
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Detailed address / Pickup point", max_length=255
                    ),
                ),
                (
                    "maps_link",
                    models.URLField(
                        blank=True, default="", help_text="Google Maps URL"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pickup Location",
                "verbose_name_plural": "Pickup Locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_ref",
                    models.CharField(
                        default=rentals.models.generate_booking_ref,
                        editable=False,
                        help_text="Unique booking reference code",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_mobile", models.CharField(max_length=20)),
                ("customer_whatsapp", models.CharField(max_length=20)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("pickup_date", models.DateField(default=datetime.date.today)),
                ("pickup_time", models.CharField(default="10:00", max_length=10)),
                ("return_date", models.DateField(default=datetime.date.today)),
                ("return_time", models.CharField(default="10:00", max_length=10)),
                ("total_days", models.PositiveSmallIntegerField(default=1)),
                ("estimated_amount", models.PositiveIntegerField(default=0)),
                ("security_deposit", models.PositiveIntegerField(default=3000)),
                (
                    "policy_accepted",
                    models.BooleanField(
                        default=True,
                        help_text="Customer accepted Vehicle Care & Damage Policy",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Owner Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Unavailable / Rejected"),
                            ("CANCELLED", "Cancelled by Customer"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_status",
                    models.CharField(
                        choices=[
                            ("NOT_SENT", "Not Sent"),
                            ("SENT", "Sent to Customer"),
                            ("FAILED", "Delivery Failed"),
                        ],
                        default="NOT_SENT",
                        max_length=20,
                    ),
                ),
                (
                    "owner_notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal owner notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rentals.car",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_bookings",
                        to="rentals.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Request",
                "verbose_name_plural": "Booking Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
