# Generated by Django 6.1.1 on 2026-10-05 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="discount_amount",
            field=models.PositiveIntegerField(
                default=0, help_text="Multi-day / promotional discount"
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("NOT_SENT", "Not Sent"),
                    ("SENT", "Sent to Customer"),
                    ("FAILED", "Delivery Failed"),
                ],
                default="NOT_SENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="net_rental_amount",
            field=models.PositiveIntegerField(
                default=0, help_text="Net rental fee payable"
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="payable_at_pickup",
            field=models.PositiveIntegerField(
                default=0, help_text="Total cash/UPI due on vehicle pickup"
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="payment_mode",
            field=models.CharField(
                default="OFFLINE_AT_PICKUP",
                help_text="Offline Cash / UPI upon vehicle inspection",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Registered customer account (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="estimated_amount",
            field=models.PositiveIntegerField(
                default=0, help_text="Gross rental amount before discount"
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="security_deposit",
            field=models.PositiveIntegerField(
                default=3000, help_text="Refundable deposit"
            ),
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mobile contact number",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="WhatsApp number for booking updates",
                        max_length=20,
                    ),
                ),
                (
                    "driving_license_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Driving License ID",
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
            },
        ),
    ]
