# Generated by Django 6.1.1 on 2026-10-06 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_bookingrequest_cancellation_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Guest phone / mobile number",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="driving_license_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Guest Driving License ID",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="customer_email",
            field=models.EmailField(
                blank=True, default="", help_text="Guest email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="customer_mobile",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alternate mobile number",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="customer_name",
            field=models.CharField(help_text="Guest full name", max_length=120),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="customer_whatsapp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="WhatsApp contact number",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff or registered user (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="WhatsApp number for updates",
                max_length=20,
            ),
        ),
    ]
