# Generated by Django 6.1.1 on 2026-10-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_bookingrequest_customer_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="Reviewer full name", max_length=120),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Renter phone number",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "★★★★★ (5/5) — Excellent"),
                            (4, "★★★★☆ (4/5) — Very Good"),
                            (3, "★★★☆☆ (3/5) — Average"),
                            (2, "★★☆☆☆ (2/5) — Below Average"),
                            (1, "★☆☆☆☆ (1/5) — Poor"),
                        ],
                        default=5,
                        help_text="Star rating (1-5)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Review headline",
                        max_length=150,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Detailed feedback on vehicle condition, drive experience, and service"
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("Vacation", "Vacation / Holiday"),
                            ("Family", "Family Trip"),
                            ("RoadTrip", "Road Trip / Weekend Drive"),
                            ("Business", "Business / Work"),
                            ("Local", "Local City Drive"),
                        ],
                        default="Vacation",
                        max_length=40,
                    ),
                ),
                (
                    "is_verified_renter",
                    models.BooleanField(
                        default=False,
                        help_text="Verified through booking reference and phone",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="Visibility status for moderation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked verified booking request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="rentals.bookingrequest",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="rentals.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Review",
                "verbose_name_plural": "Customer Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
